import { Button } from "./Button";

export function Dialpad({ setoutput, output, themeValue }) {
  return (
    <div className={`dial-pad${themeValue}`}>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        7
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        8
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        9
      </Button>
      <Button
        cname={`special-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        DEL
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        4
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        5
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        6
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        +
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        1
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        2
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        3
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        -
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        .
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        0
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        /
      </Button>
      <Button
        cname={`num-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        x
      </Button>
      <Button
        cname={`reset-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        RESET
      </Button>
      <Button
        cname={`calculate-btn${themeValue}`}
        setoutput={setoutput}
        output={output}
      >
        =
      </Button>
    </div>
  );
}
